# Generated by Django 5.1.4 on 2024-12-19 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emi",
            name="linked_savings_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finapp.savingsaccount",
                verbose_name="Linked Savings Account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="savings_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finapp.savingsaccount",
                verbose_name="Savings Account",
            ),
        ),
    ]
