# Generated by Django 5.1.4 on 2025-01-26 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0002_emi_linked_savings_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='CREATED'),
        ),
    ]
